apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app 
    spec:
      containers:
      - name: nodejs-app
        image: noorjahansn/nodejsappeg:IMAGE_VERSION_PLACEHOLDER
        ports:
        - containerPort: 3000
